description = "a lighting shell"
externalLinkDecoration = true

displayUpdatedDate = true
dateFormat = "2006年1月2日"

colorScheme = "one-light"
# autumn avocado bloody blowfish congo fire forest github marvel neon noir one-light princess slate terminal
enableA11y = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true
# mainSections = ["doc"]
defaultBackgroundImage = "images/coderain.svg" # used as default for background images
defaultFeaturedImage = "images/featured.svg" # used as default for featured images in all articles
defaultSocialImage = "/android-chrome-512x512.png" # used as default for social media sharing (Open Graph and Twitter)


# defaultBackgroundImage = "/images/ripples.svg"
# defaultFeaturedImage = "/img/featured.svg"
# defaultSocialImage = "/img/blowfish_banner.png"
# hotlinkFeatureImage = false

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false
# [header]
#   layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[author]
name = "Lume shell"
image = "/images/logo.svg"
# headline = "A generally awesome human"
# bio = "A little bit about me"
# links = [
#   { twitter = "https://twitter.com/username" }
# ]

[homepage]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = true
  layout = "hero" # valid options: page, profile, hero, card, background, custom
  # homepageImage = "img/coderain0.svg" # used in: hero, and card
  showRecent = true
  showRecentItems = 3
  showMoreLink = true
  # showMoreLinkDest = "/practice/"
  cardView = true
  cardViewScreenWidth = false
  disableHeroImageFilter = false # only used when layout equals hero


[list]
  showHero = true
  heroStyle = "card"
  layoutBackgroundBlur = false # only used when heroStyle equals background
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = true
  orderByWeight = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
  constrainItemsWidth = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = false
  # showAuthorBottom = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true # use showTaxonomies OR showCategoryOnly, not both
  showCategoryOnly = false # use showTaxonomies OR showCategoryOnly, not both
  showAuthorsBadges = false
  showWordCount = true
  # sharingLinks = [ "linkedin", "twitter", "bluesky", "mastodon", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram", "line"]
  showZenMode = true
  # externalLinkForceNewTab = false # disable to allow external links in the same tab (defaults to true)

[header]
  layout = "fixed-blur" # valid options: basic, fixed, fixed-fill, fixed-gradient, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true
